### ISSUE TITLE
Does 'knife azure server create' support asynchronous request？

### ISSUE THREAD

**Issue by bluesky8640** [chef/knife-azure#140]
Dear all,

I use 'knife azure' to manage my azure infrastructure. But I found 'knife azure server create' was a synchronous request, which means I must wait for one VM's creation completed to create a next VM.

Does 'knife azure server create' support asynchronous request? I want to send multiple 'knife azure server create' request at the same time to create VMs simultaneously.

Thanks,
Chao Jin

**Comment by adamedx** [comment]
For asynchronous requests, try using the `--bootstrap-protocol cloudapi` option or the new `knife azurerm server create` available on the master branch. ARM commands will get around some limitations in the older API with concurrent requests.
