### ISSUE TITLE
Typo in RAEDME.md

### ISSUE THREAD

**Issue by jeffjia** [chef/knife-azure#141]
knife azure server create -N MyNewNode --azure-vm-size Medium --I 8fcc3d_Ubuntu-12_04-amd64-30GB -m 'West US' --ssh-user myuser --identity-file ~/.ssh/myprivatekey_rsa

should be

    knife azure server create -N MyNewNode --azure-vm-size Medium -I 8fcc3d_Ubuntu-12_04-amd64-30GB -m 'West US' --ssh-user myuser --identity-file ~/.ssh/myprivatekey_rsa

Using `--I` causes

    ERROR: You did not provide a valid 'Azure Source Image' value. Please set knife[:azure_source_image] in your knife.rb or pass as an option.`

**Comment by adamedx** [comment]
This seems to have been resolved in the latest README.md -- thank you for reporting this.
