### ISSUE TITLE
Provisioning Azure VM with SSH identity file - why failing on password?

### ISSUE THREAD

**Issue by magaal** [chef/knife-azure#145]
Hi all - not sure why this is happening, here's my output:

azureuser@*****:~$ knife azure server create -N MyNewNodet --azure-vm-size Small --azure-source-image "0b11de9248dd4d87b18621318e037d37__RightImage-Ubuntu-12.04-x64-v5.8.8.8" -m 'West US' --ssh-us
er azureuser --identity-file ~/myPrivateKey.key
............
Waiting for virtual machine to reach status 'provisioning'............vm state 'provisioning' reached after 2.58 minutes.
.
DNS Name: *****************
VM Name: *******************
Size: Small
Azure Source Image: 0b11de9248dd4d87b18621318e037d37__RightImage-Ubuntu-12.04-x64-v5.8.8.8
Azure Service Location: West US
Public Ip Address: ****************
Private Ip Address: ********************
SSH Port: 22
Environment: _default

Waiting for sshd on *************:22done

Connecting to *****************
**************** [sudo] password for azureuser: Sorry, try again.
**************** [sudo] password for azureuser:
**************** Sorry, try again.
**************** [sudo] password for azureuser:
**************** Sorry, try again.
**************** sudo: 3 incorrect password attempts

If I ssh azureuser@ip and accept the thumbprint I connect just fine without a password - is there a specific reason why the knife bootstrap is trying a password?

**Comment by siddheshwar-more** [comment]
I think this is resolved !
