### ISSUE TITLE
dpkg status database is locked by another process, chef client install fails

### ISSUE THREAD

**Issue by magaal** [chef/knife-azure#147]
Running into this inconsistently - some kind of race condition? Using this command...

 knife azure server create - --azure-vm-size Small --azure
-dns-name 'chefsrv90' --azure-vm-name 'chefsrv90' --azure-affinity-group chefnet
 -r "role[webserver]" --azure-network-name chefnet --tcp-endpoints 80:80,8080:80
80

provisions, then once its up during client install:

 to file /tmp/install.sh.1434/chef_11.12.4-1_amd64.deb
 trying wget...
 Comparing checksum with sha256sum...
 Installing Chef 11.12.4
installing with dpkg...
pkg: error: dpkg status database is locked by another process
Installation failed
 Please file a bug report at http://tickets.opscode.com
 Project: Chef
Component: Packages
Label: Omnibus
Version: 11.12.4
Please detail your operating system type, version and any other r
elevant details
Starting first Chef Client run...
bash: line 90: chef-client: command not found

**Comment by siddheshwar-more** [comment]
@magaal 

Can we close this issue?

**Comment by magaal** [comment]
Yes, sorry! This worked.

Sent from Outlook<http://taps.io/outlookmobile>




On Mon, May 25, 2015 at 3:14 AM -0700, "Siddheshwar More" <notifications@github.com<mailto:notifications@github.com>> wrote:


@magaal<https://github.com/magaal>

Can we close this issue?

-
