### ISSUE TITLE
Does not play nicely with chefdk

### ISSUE THREAD

**Issue by mattstratton** [chef/knife-azure#148]
There seems to be a rdoc conflict with chefdk. When installing knife-azure with the chef gem install command, the following occurs with any knife commands:

```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2064:in `raise_if_conflicts': Unable to activate knife-azure-1.2.2, because rdoc-4.1.0 conflicts with rdoc (~> 3.12) (Gem::LoadError)
```

**Comment by AnneTheAgile** [comment]
@mattstratton , now that @kaustubh-d said the rdoc dependency is removed, does it work for you and we can close this?
AnneTheAgile

**Comment by siddheshwar-more** [comment]
@AnneTheAgile @mattstratton 
We have verified this with chef-dk v0.6.0 and its working fine.
