### ISSUE TITLE
what version of chef is supported?

### ISSUE THREAD

**Issue by mg03** [chef/knife-azure#165]
Hi

I am using the open source version-11 chef server/knife/client all on ubuntu machines. What version of chef will work with the knife-azure plugin?

regards

meher

**Comment by AnneTheAgile** [comment]
@mg03 , did you fix the problem? What OS / version are you on? 

I am here wondering if Chef Knife can be installed on a windows machine.

**Comment by btm** [comment]
@AnneTheAgile yes, you can use knife on Windows. Download Chef-DK or the Windows client from  https://downloads.chef.io/. You can install the knife-azure gem into it as well. When using Chef-DK you can run 'chef gem install knife-azure'.

**Comment by AnneTheAgile** [comment]
@btm  thank you! I will be trying it all out soon I hope.

**Comment by NimishaS** [comment]
@AnneTheAgile , is your issue resolved? Can we close this?

**Comment by siddheshwar-more** [comment]
@mg03 
Its working fine at our side with knife-azure version 1.3.0 and released one.
