### ISSUE TITLE
knife azure server create failing

### ISSUE THREAD

**Issue by waghpravin14** [chef/knife-azure#166]
Have been trying to create azure vm using knife using a hosted chef server but have been failing to do so . It waits for winrm to respond and then finally kills itself.

Can someone please provide me help to get me unblocked its very urgent for me to move ahead from here.

Any help will be highly appreciated.
Thanks in advance.

PS C:\chef-repo> knife azure server create --azure-connect-to-existing-dns --azure-dns-name chefnode --azure-vm-name 'node5' --azure-service-location 'East Asia' --azure-source-image 'bd507d3a70934695bc2128e3e5a255ba__RightImage-Windows-2008R2-SP1-x6

4-iis75-v5.8.8' --winrm-user 'node' --winrm-password 'node12!@' --bootstrap-protocol winrm --distro 'windows-chef-client-msi'

..........

Waiting for virtual machine to reach status 'provisioning'............vm state 'provisioning' reached after 2.85 minutes.

Waiting for virtual machine to reach status 'ready'..........................vm state 'ready' reached after 6.76 minutes.

.

DNS Name: chefnode.cloudapp.net

VM Name: node5

Size: Small

Azure Source Image: bd507d3a70934695bc2128e3e5a255ba__RightImage-Windows-2008R2-SP1-x64-iis75-v5.8.8

Azure Service Location: East Asia

Public Ip Address: 168.63.212.145

Private Ip Address: 100.80.52.52

WinRM Port: 47077

Environment: _default

Waiting for winrm on 168.63.212.145:47077

Waiting for remote response before bootstrap.WARNING: Unsupported version of httpclient. The supported major version of library is httpclient version 2.4. This code path monkey patches few methods in httpclient to support additional features. This co

uld possibly work, but it is advised to extensively test your version. If you are aware of the impact of using 2.5.0, this warning can be disabled by setting USE_HTTPCLIENT_MAJOR to the major version 2.5.

ERROR: No response received from remote node after 0.01 minutes, giving up.

ERROR: RuntimeError: Command execution failed.

PS C:\chef-repo>

Thanks,
Pravin

**Comment by AnneTheAgile** [comment]
@waghpravin14 , did you get this solved? I take it you have installed knife-azure on your Windows (7?) local machine and you had trouble getting Azure to fully respond? 
 AnneTheAgile

**Comment by siddheshwar-more** [comment]
@waghpravin14 
Can you also set following and try again ?
winrm set winrm/config/winrs @{MaxMemoryPerShellMB="1000"}

**Comment by adamedx** [comment]
@waghpravin14 we've released a new version of knife-azure (1.4.0) -- could you attempt to repro and let us know how things go? Also, setting the winrm settings above would be helpful as well.

**Comment by adamedx** [comment]
Closing since we haven't heard any more reports on this.
