### ISSUE TITLE
Azure China support

### ISSUE THREAD

**Issue by aiman-alsari** [chef/knife-azure#199]
Hi,

Is there any support for Azure China? I suspect it has some minor differences - Has anyone else tested it? I notice that it isn't in the region list in the documentation (although these are only examples..).

Thanks,
Aiman

**Comment by adamedx** [comment]
I haven't tried it, but if you have access to Azure China, you might be able to configure `knife-azure` to talk to it using the `--azure-api-host-name` option for each subcommand (create, list, etc.).

**Comment by NimishaS** [comment]
@aiman-alsari, this fix has been merged in master branch.

**Comment by aiman-alsari** [comment]
Thank you
