### ISSUE TITLE
Duplicate short-name option in server create command

### ISSUE THREAD

**Issue by adamedx** [chef/knife-azure#201]
Both the --distro and --azure-dns-name options have a short -d option. The --azure-dns-name option should not have the -d option. Additionally, we should have a test that verifies that there are no duplicate short or long options that would have failed in this case.

**Comment by kaustubh-d** [comment]
We found -d for --distro but not there for --azure-dns-name. We checked this on master branch and released knife-azure.

**Comment by adamedx** [comment]
Thanks for looking @kaustubh-d, that must have been a doc-only bug, probably leftover from earlier fixes to duplicate options.
