### ISSUE TITLE
knife-azure should allow script extension to be used when doing winrm bootstrap to set winrm timeouts

### ISSUE THREAD

**Issue by adamedx** [chef/knife-azure#203]
We should allow an option in knife-azure to allow the script extension to run before bootstrap when winrm is used (not cloud-api). The user can then specify a powershell script as a string that can be run by the VM script extension to do things like set the winrm timeout, which is useful for Win2k8r2 systems that have a bad winrm config.

**Comment by odlevakp** [comment]
I would love it - especially have the ability to specify a script after instance creation. Currently I have no way to launch a stock Windows server image, because winrm remote connections are disabled by default. On Amazon knife-ec2 supports user data, but for Azure I'm out of luck.

**Comment by schisamo** [comment]
@odlevakp Take a look at https://github.com/chef/knife-azure/pull/204. Needs a little tweaking per feedback from @adamedx but it works with stock images.
