### ISSUE TITLE
Unable to provision a VM into a load balanced set

### ISSUE THREAD

**Issue by aiman-alsari** [chef/knife-azure#205]
Given the following setup:

* Provision VM *vm1* into cloud service *cs1* using knife-azure.
* Configure *vm1* using the management portal. Add a stand alone endpoint on Port 80 and make that endpoint part of a load balanced set, *lbs1*.

I expect to be able to provision a new VM, *vm2* in *cs1* using *lbs1* but I can not.
Even better, I want to be able to have *lbs1* created when I create *vm1* and then be able to add more VMs to *lbs1* later.

**Comment by aiman-alsari** [comment]
This is possible using LoadBalancedEndpointSetName

https://msdn.microsoft.com/en-us/library/azure/jj157194.aspx#nwcInputEndpoints

**Comment by aiman-alsari** [comment]
I'm looking at adding the feature myself.

**Comment by siddheshwar-more** [comment]
@aiman-alsari 
That's great. Let us know if you need any help.

**Comment by aiman-alsari** [comment]
@siddheshwar-more - It's a bit more complicated than I originally thought. I can create the load balanced set fairly easily if it is the first VM in that set - but adding a second VM to an existing LB set requires a subsequent Update Role after Add Role has completed.

It will require changing role.rb quite substantially. I will perform the change, but be aware that it may not be pretty.

**Comment by aiman-alsari** [comment]
Scratch that last comment - turns out it can all be done via Add Role.

**Comment by aiman-alsari** [comment]
Hi @siddheshwar-more @adamedx @NimishaS @prabhu-das and any other contributors.

I'm looking at finding a good way to specify endpoints. There are 5 parameters that need to be specified.

Public Port 
Internal Port (Optional, defaults to public port)
LB set name (Optional, default is no Load balancing)
LB probe HTTP path (Optional, default is TCP probe on public port, only relevant if LB set name is specified)
Internal Load Balancer name (Optional)

The existing way to do this in master was for only 2 fields, Public and Internal ports.
e..g {local_port}:{internal_port}

I have modified this to add in LB set name and LB probe path so that it looks like:
{localPort}:{publicPort}:{load_balancer_set_name}:{load_balancer_probe_path}

As I am now wanting to add a 5th field (Internal Load Balancer name) it is starting to get unwieldy.

The options are:
1) Add it onto the existing endpoints string and make it cumbersome.
2) Split the endpoint string out into multiple parameters and allow them to be specified when calling azure_server_create (there are already very many)
3) Have some other data structure.

Any recommendations? The easiest thing for me is Option 1, which I will do, just to get things going for my own sake - but do let me know if you prefer another option.

Thanks

**Comment by siddheshwar-more** [comment]
@aiman-alsari 
Sorry for delay was busy with other stuff
#1 looks good, but problem is user has to specify port details in same order ( So, I'm thinking about JSON format like --tcp-endpoints {local_port:80,public_port:80,load_balancer_set_name:teslbs}, {...} ) 

#2 is not possible in our case as user can specify multiple tcp_endpoints, So having extra options like `--load-balance-set-name` won't helpful in this case. 

Thank you for your contribution .

**Comment by siddheshwar-more** [comment]
@aiman-alsari 
Do you have any Pull Request for this issue?

**Comment by aiman-alsari** [comment]
Yes it's been sitting there for a while:

https://github.com/chef/knife-azure/pull/210

It might need a bit of work, as I took the easy option as discussed above.

**Comment by siddheshwar-more** [comment]
@aiman-alsari 
Thank you for your contribution, we are verifying your changes.
