### ISSUE TITLE
server create -> --environment and --json-attributes not working?

### ISSUE THREAD

**Issue by scottgerring** [chef/knife-azure#207]
On knife-azure 1.4.0, neither --environment or --json-attributes seem to be propogated to my (Linux) machine, either at runtime on the node or back to the chef server subsequent to a successful run. Are these features working, and if so, are there any caveats on their usage? If not, is there another mechanism I can use to pass run-specific information to a machine? 

thanks,

Scott.

**Comment by Vasu1105** [comment]
@scottgerring Could you please let me know chef version and what command you are trying to run.

**Comment by Vasu1105** [comment]
@scottgerring Could you please post the log with -VV option for this issue ?

**Comment by NimishaS** [comment]
@scottgerring , we are tracking this issue as one of our tasks. Could you please comment if the issue still persists for you?

**Comment by scottgerring** [comment]
Sorry guys, as some time has passed I no longer have access to the system this was occuring on and cannot reproduce the issue from scratch. FYI I ended up using the Azure powershell modules to achieve the same.
