### ISSUE TITLE
Compatible with Windows Azure Pack?

### ISSUE THREAD

**Issue by cstewart87** [chef/knife-azure#212]
Has anyone tested this to see if it's compatible with the on-prem Windows Azure Pack (WAP)?

**Comment by smurawski** [comment]
Not that I'm aware of.  You are welcome to try, but I believe that while the WAP API's are close to the Windows Azure Service Management APIs, they differ a bit.

Given that WAP is pretty much in sustained engineering and there isn't any new investment in the Service Management API (in favor of the forthcoming AzureStack and Azure RM APIs), I don't think there is much to be gained in building in support.

**Comment by btm** [comment]
@smurawski that makes sense. thanks.

@cstewart87 I'm going to close this. If you're using Windows Azure Pack and you find that knife-azure works or almost works, we'd accept patches to fix minor issues. But I don't see us writing any major features for Windows Azure Pack given the newer products in the space that appear to have wider acceptance.
