### ISSUE TITLE
Add --[no-]node-verify-api-cert

### ISSUE THREAD

**Issue by cparedes** [chef/knife-azure#219]
It looks like we construct a client.rb file to ship via cloud-api (and possibly bootstrap templates as well if we're doing WinRM) - it'd be great to have support for specifying --[no-]node-verify-api-cert in order to slip in an option in client.rb to not verify the Chef Server SSL certificate in the case of using self-signed certificates.

**Comment by siddheshwar-more** [comment]
Hello, @cparedes  
We are working on this. Thank you !

**Comment by siddheshwar-more** [comment]
@cparedes 
We have fixed this in https://github.com/chef/knife-azure/pull/227/files.
You can use this feature once we release next Chef Extension's version.
Thank you!

**Comment by mfdii** [comment]
Do we know when this is going to be released?
