### ISSUE TITLE
server create issue: ProvisioningConfigurationSet must be specified.

### ISSUE THREAD

**Issue by acornies** [chef/knife-azure#235]
I'm trying to create a vm with knife-azure using:

```
knife azure server create -VV --azure-dns-name 'example-vm-name' --azure-vm-size 'Basic_A2' --azure-service-location 'Japan West' --azure-source-image 'example-image-name'
```

but consistently getting: 

```
A ProvisioningConfigurationSet was not found in the ConfigurationSet collection of the virtual machine with name <name>. When creating a virtual machine from an image, ProvisioningConfigurationSet must be specified.
```

I have the ssh_user, identity_file and publish_settings file set correctly in knife.rb, but the xml that gets generated doesn't include ProvisioningConfigurationSet. Is this a new or known issue? 

using: 
Chef: 12.3.0
knife-azure: 1.4.0

**Comment by Vasu1105** [comment]
@acornies I wasn't able to reproduce this issue. Are you still facing this issue ? And can you send the log with -VV option .

**Comment by Vasu1105** [comment]
@acornies if you come across this issue again feel free to reopen it
