### ISSUE TITLE
UX on knife azure server delete prompt is misleading

### ISSUE THREAD

**Issue by ricardolupo** [chef/knife-azure#242]
The prompt for `knife azure server delete` should allow upper and lower case [y|Y] or allow the literal string being requested.

```Do you really want to delete this server? (Y/N) Y
I have no idea what to do with 'Y'
Just say Y or N, please.
Do you really want to delete this server? (Y/N) y```

**Comment by vinyar** [comment]
:+1:

**Comment by andrewelizondo** [comment]
This code [here](https://github.com/chef/knife-azure/blob/master/lib/chef/knife/azure_server_delete.rb#L126) is actually calling the confirm method from the core knife ui [here](https://github.com/chef/chef/blob/master/lib/chef/knife/core/ui.rb#L267-L272).

This issue should be created against chef itself, not knife-azure. So I'm closing this issue.
