### ISSUE TITLE
knife[:azure_api_host_name] setting does not accept http url

### ISSUE THREAD

**Issue by vinyar** [chef/knife-azure#248]
Bug: specifying the full Azure URL in the knife.rb causes `knife azure` commands to fail.
Expectation: specifying the full URL should work.

Azure docs and config files use the full https URL
example from azureProfile.json:
`"managementEndpointUrl": "https://management.core.windows.net"`
example from myazure.publishsettings:
`ServiceManagementUrl="https://management.core.windows.net"`

I think the knife setting should accept both, the short URL as it has presently (to avoid breaking current users) and in the full https:/... format.

**Comment by siddheshwar-more** [comment]
@vinyar We are looking into this.

Thank you !

**Comment by adamedx** [comment]
@vinyar, how did you encounter this? I'd like to understand if you ended up losing lots of time because the name format wasn't clear, or if the tool was very specific and said that the name had to be in a different format.

**Comment by vinyar** [comment]
Hi. Didn't spend a whole lot of time on it. Maybe 20-30 min?

The scenario was: I was ramping up on various azure drivers, and when I got to knife, entered the same url for `knife[:azure_api_host_name]` as the other drivers.

**Comment by Vasu1105** [comment]
Fixed here #268
