### ISSUE TITLE
(pending validation) Knife server delete is limited to ~5 servers in a list

### ISSUE THREAD

**Issue by vinyar** [chef/knife-azure#259]
Command:
`knife azure server delete 'machine01' 'machine02' 'machine03' 'machine04' 'machine05' 'machine06' --purge -y`

Bug: 
Machine06 was not deleted from Azure.  It didn't even get listed in the command's output of work it was performing.

/cc: @msnahill for more info

**Comment by adamedx** [comment]
Thanks @vinyar, this is being investigated. In the meantime, if you're using PowerShell, I recommend something like this which is actually more idiomatic though probably slower:

```powershell
('machine01', 'machine02', 'machine03', 'machine04') | foreach { knife azure server delete  "$_" -y --purge }
```

**Comment by vinyar** [comment]
@adamedx :+1: yup. I agree that for a knife based workflow your suggestion will be the better way to go.

**Comment by Vasu1105** [comment]
@vinyar, we tried deleting 6 and 7 VMs and the command ran successfully. 
Here is the command with the output-
```
$ knife azure server delete 'k-ubu-23-30' 'k-ubu-23-31' 'k-ubu-23-32' 'k-ubu-23-33' 'k-ubu-23-34' 'k-ubu-23-35' 'k-ubu-23-36' --purge -y -c ~/chef-repo/.chef/knife.rb 

...........................
DNS Name: k-ubu-23-30.cloudapp.net
VM Name: k-ubu-23-30
Size: Small
Public Ip Address: 23.99.80.185

..
WARNING: Deleted server k-ubu-23-30
WARNING: Deleted node k-ubu-23-30
WARNING: Deleted client k-ubu-23-30

DNS Name: k-ubu-23-31.cloudapp.net
VM Name: k-ubu-23-31
Size: Small
Public Ip Address: 104.40.94.244

..
WARNING: Deleted server k-ubu-23-31
WARNING: Deleted node k-ubu-23-31
WARNING: Deleted client k-ubu-23-31

DNS Name: k-ubu-23-32.cloudapp.net
VM Name: k-ubu-23-32
Size: Small
Public Ip Address: 138.91.244.254

..
WARNING: Deleted server k-ubu-23-32
WARNING: Deleted node k-ubu-23-32
WARNING: Deleted client k-ubu-23-32

DNS Name: k-ubu-23-33.cloudapp.net
VM Name: k-ubu-23-33
Size: Small
Public Ip Address: 40.112.188.67

..
WARNING: Deleted server k-ubu-23-33
WARNING: Deleted node k-ubu-23-33
WARNING: Deleted client k-ubu-23-33

DNS Name: k-ubu-23-34.cloudapp.net
VM Name: k-ubu-23-34
Size: Small
Public Ip Address: 40.78.110.138

..
WARNING: Deleted server k-ubu-23-34
WARNING: Deleted node k-ubu-23-34
WARNING: Deleted client k-ubu-23-34

DNS Name: k-ubu-23-35.cloudapp.net
VM Name: k-ubu-23-35
Size: Small
Public Ip Address: 40.78.107.248

..
WARNING: Deleted server k-ubu-23-35
WARNING: Deleted node k-ubu-23-35
WARNING: Deleted client k-ubu-23-35

DNS Name: k-ubu-23-36.cloudapp.net
VM Name: k-ubu-23-36
Size: Small
Public Ip Address: 40.118.213.117

..
WARNING: Deleted server k-ubu-23-36
WARNING: Deleted node k-ubu-23-36
WARNING: Deleted client k-ubu-23-36
```

**Comment by vinyar** [comment]
/cc: @msnahill - can you see if you're still having an issue with new gem?

**Comment by vinyar** [comment]
@Vasu1105 Hi, my example wasn't very reflective of the actual command. 

The names of the nodes in the bug are actually much longer: "msftservername1.redmond.microsoft.subdom.com" - meaning, if there is an some kind of string limit, your example may still be under the limit.

**Comment by NimishaS** [comment]
@vinyar , are you passing `msftservername1.redmond.microsoft.subdom.com` as `--azure-dns-name` or `--node-name`? It seems more like an FQDN.

**Comment by vinyar** [comment]
We were not passing a name actually. Node name was populated automatically.
The knife command automatically joined nodes to a domain, resulting in long names.

**Comment by btm** [comment]
@NimishaS could we try creating 6 vms and then deleting them, and make sure they're long names like,

```
knife azure server delete '1234567801234567890-k-ubu-23-30' '1234567801234567890-k-ubu-23-31' '1234567801234567890-k-ubu-23-32' '1234567801234567890-k-ubu-23-33' '1234567801234567890-k-ubu-23-34' '1234567801234567890-k-ubu-23-35' '1234567801234567890-k-ubu-23-36' --purge -y -c ~/chef-repo/.chef/knife.rb 
```

If that doesn't work we should close this as unreproducible given how long it has say.

**Comment by Vasu1105** [comment]
@vinyar & @btm we have verified the vm with long names. I created 6 vm's with long names and able to delete it successfully.

**Comment by Vasu1105** [comment]
@vinyar closing this issue as its not reproducible at our end.
