### ISSUE TITLE
knife azure should support ssl cert bootstrap with cloud-api bootstrap

### ISSUE THREAD

**Issue by vinyar** [chef/knife-azure#260]
When using winrm or ssh, knife will automatically copy over ssl certs to the node being bootstrapped. This should also be done with cloud-api bootstrap.
Support will be needed in both the azure_chef_extension and in knife-azure.

re: https://chefio.atlassian.net/browse/CLOGENG-134

@msnahill

**Comment by adamedx** [comment]
Resolved with https://github.com/chef/knife-azure/pull/261.

**Comment by vinyar** [comment]
:+1:
