### ISSUE TITLE
knife azure server create using ARM templates

### ISSUE THREAD

**Issue by spbreed** [chef/knife-azure#285]
Would there be any functionality to create Azure resources such as VM using Azure ARM JSON templates?

https://github.com/Azure/azure-quickstart-templates

**Comment by stuartpreston** [comment]
Not in knife currently, but you could take a look at https://github.com/pendrica/chef-provisioning-azurerm

**Comment by adamedx** [comment]
@spbreed, can you clarify the scenario? You're asking if you can supply knife-azure a template? In that case, there's no guarantee the template even provisions VM's, it might provision other things such as storage, etc., that are not directly managed by Chef. In that case, I don't quite see how `knife-azure` which is oriented around provisioning VM's with Chef integration is a consumer of user-supplied ARM templates. I think @stuartpreston's approach is more what you'd want in this scenario.

**Comment by Vasu1105** [comment]
@spbreed we are not supporting passing template currently since using template you can create other things as mentioned by @adamedx.  Hence we are not supporting this currently.
