### ISSUE TITLE
FATAL: The x-ms-version header value '2014-05-01' is not one of the supported version headers.

### ISSUE THREAD

**Issue by sofam** [chef/knife-azure#286]
When deploying with the following command, using knife-azure 1.6.0rc0 I get the error in the subject. 
If I actively change the header value in the gem to `request["x-ms-version"] = "2015-04-01"`, it works fine.

Could you please bump it to 2015-04-01?

`knife azure server create --azure-dns-name "future01" --azure-vm-size Standard_DS2  --azure-service-location 'North Europe' --winrm-user kekkonen1 --winrm-password 'lolophone' --run-list "nightly" --environment "azure-nightly" -VV`

**Comment by Vasu1105** [comment]
Fixed here https://github.com/chef/knife-azure/blob/fe3df28af9c32b490886a2aa0cfbdfaab60d3b11/lib/azure/service_management/rest.rb
