### ISSUE TITLE
Error provisioning VM in existing Cloud service

### ISSUE THREAD

**Issue by sernapallyanurag** [chef/knife-azure#309]
.ERROR: Virtual machine state 'provisioning' not reached after 20 minutes.
ERROR: Failed to create the server -- exception being rescued: Verify connectivity to Azure and subscription resource li
mit compliance (e.g. maximum CPU core limits) and try again.

I am unable to understand what this means.

**Comment by NimishaS** [comment]
@sernapallyanurag, please share the command that you ran and also the logs with `-VV` option

**Comment by sernapallyanurag** [comment]
knife azure server create --azure-vm-size 'Small' --azure-connect-to-existing-dns 'mydns' --azure-dns-name 'mydns' --azure-service-location 'Southeast Asia' --azure-vm-name 'testsonar' --azure-source-image 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20160201-en-us-30GB' --ssh-user 'ubuntu' --ssh-password '*****' --tcp-endpoints 80:8080,443,9000,8989,5672,3389' --run-list 'role[sonar_role]'

**Comment by sernapallyanurag** [comment]
INFO: calling get hostedservices/mydns synchronously
.INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
.
Waiting for virtual machine to reach status 'provisioning'INFO: calling get hostedservices/sonatacir/deploymentslots/Pro
duction synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/sonatacir/deploymentslots/Production synchronously
..INFO: calling get hostedservices/sonatacir/deploymentslots/Production synchronously
..INFO: calling get hostedservices/sonatacir/deploymentslots/Production synchronously
..INFO: calling get hostedservices/sonatacir/deploymentslots/Production synchronously
..INFO: calling get hostedservices/sonatacir/deploymentslots/Production synchronously
..INFO: calling get hostedservices/sonatacir/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..INFO: calling get hostedservices/mydns/deploymentslots/Production synchronously
..ERROR: Virtual machine state 'provisioning' not reached after 10 minutes.
ERROR: Failed to create the server -- exception being rescued: Verify connectivity to Azure and subscription resource li
mit compliance (e.g. maximum CPU core limits) and try again.
DEBUG: RuntimeError: Verify connectivity to Azure and subscription resource limit compliance (e.g. maximum CPU core limi
ts) and try again.
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-azure-1.4.0/lib/chef/knife/azure_server_create.rb:295:i
n `rescue in wait_until_virtual_machine_ready'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-azure-1.4.0/lib/chef/knife/azure_server_create.rb:263:i
n `wait_until_virtual_machine_ready'
C:/Users/anurag.s/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-azure-1.4.0/lib/chef/knife/azure_server_create.rb:517:i
n `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/knife.rb:405:in `block in run
_with_pretty_exceptions'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_ser
ver_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/knife.rb:404:in `run_with_pre
tty_exceptions'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/knife.rb:203:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/knife.rb:142:in `
run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1-universal-mingw32/bin/knife:25:in `<top (required)>'
C:/opscode/chefdk/embedded/bin/knife:23:in `load'
C:/opscode/chefdk/embedded/bin/knife:23:in `<main>'
WARNING: Cleaning up resources...

**Comment by Vasu1105** [comment]
@sernapallyanurag use auth_timeout option in server create to avoid this error. You can refer #189 and #190 for this.

**Comment by sernapallyanurag** [comment]
Mine is a ubuntu VM not windows.

**Comment by sernapallyanurag** [comment]
Its fixed. It was a an endpoint issue. Thanks a lot for response.
