### ISSUE TITLE
create server does not install azure vm agent

### ISSUE THREAD

**Issue by cjohannsen81** [chef/knife-azure#316]
Hi,

I created two azure VM´s (classic). One manually in the portal, one with knife-azure and the same parameters (imageId etc.) and the manual one has the azure vm agent installed, the knife-azure deployed one not. So remote-access is not possible.

Cheers
Christian

**Comment by stuartpreston** [comment]
Did you specify the ```--bootstrap-protocol 'cloud-api'``` as directed here: https://github.com/chef/knife-azure#cloud-api-bootstrap-feature ?

**Comment by stuartpreston** [comment]
Or were you talking about the VM agent itself (the lack of this would mean no endpoints would be opened if I remember correctly)?

**Comment by cjohannsen81** [comment]
Hey, I tried both. The msi and the cloud API. Both have no in vm agent installed in the new vm but the manual created one has.

**Comment by Vasu1105** [comment]
@cjohannsen81  - Could you please add the details about the command you are trying to do this ?

**Comment by Vasu1105** [comment]
@cjohannsen81 - Any updates on this ?

**Comment by Vasu1105** [comment]
@cjohannsen81  If I am getting it correctly you are not able to access the vm remotely. I verified that 'ProvisionGuestAgent' is set to true by knife-azure as mentioned [here](https://msdn.microsoft.com/en-us/library/azure/jj157194.aspx) in docs. Use --tcp-endpoints option to open ssh or rdp port. And let me know that solves your issue.

**Comment by Vasu1105** [comment]
@cjohannsen81 closing this for now. If you face the issue even using --tcp-endpoints option as mentioned above you can re-open this issue and provide us the details of command that you are trying
