### ISSUE TITLE
Creation of AD application and service principal is not automated for ARM commands

### ISSUE THREAD

**Issue by NimishaS** [chef/knife-azure#341]
User needs to create AD application and service principal manually right now as specified here https://github.com/chef/knife-azure#arm-mode.

**Comment by NimishaS** [comment]
@stuartpreston, do you have any library which can help in resolving this issue?

**Comment by stuartpreston** [comment]
@nimishas I did create a utility that takes AAD credentials and creates applications and performs role assignment. See http://GitHub.com/Pendrica/azure-credentials

**Comment by NimishaS** [comment]
@stuartpreston , thanks for sharing this :)

**Comment by dheerajd-msys** [comment]
@stuartpreston , thanks for the link.
This works perfectly for AD accounts. However we want to support Microsoft account users too which may require UI based interactive authentication. We would also like to handle the 2 factor/layer authentication similar to how Xplat-cli or Powershell handles it through Azure login Page.
Let us know if you have any suggestions

**Comment by stuartpreston** [comment]
I don't have anything specific on Microsoft accounts yet. The purpose of the tool was to avoid all UI and popups etc. where possible.  I have an idea how to do things for non-2FA Microsoft accounts and Federated Accounts (which is another scenario you may need to support). But for 2FA I think we'll need the equivalent of the device logon. It's an awkward area with a big spread of possible scenarios.

**Comment by NimishaS** [comment]
This issue gets resolved here: https://github.com/chef/knife-azure/pull/359
