### ISSUE TITLE
Knife-Azure Unable to Create a new VM using my custom vm image -

### ISSUE THREAD

**Issue by shridevops15** [chef/knife-azure#342]
I am trying to create a new vm using my custom virtual image. It is creating a instance and finally at the end it displays Server not created.

Please find the below command which I've used. 

Command: knife azure server create -N azuredev01 --azure-vm-size Medium --azure-source-image ecint-std-centos67-v01 --azure-service-location 'Central US' --azure-storage-account saclrsdigmv01  --ssh-user admin --ssh-password '******'

Then the result is as follows

...WARN: ResourceNotFound : The hosted service does not exist.
WARN: Unable to find hosted(cloud) service:ResourceNotFound : The hosted service does not exist.
......WARN: ResourceNotFound : No deployments were found.
....
Waiting for virtual machine to reach status 'provisioning'..........vm state 'provisioning' reached after 2.14 minutes.
.
DNS Name: az-2643f1ee5630.cloudapp.net
VM Name: az-2643f1ee5630
Size: Medium
Azure Source Image: ecint-std-centos67-v01
Azure Service Location: Central US
Private Ip Address: 100.106.84.20
Environment: _default

.
DNS Name: az-2643f1ee5630.cloudapp.net
VM Name: az-2643f1ee5630
Size: Medium
Azure Source Image: ecint-std-centos67-v01
Azure Service Location: Central US
Private Ip Address: 100.106.84.20
Environment: _default

FATAL: server not created

**Comment by shridevops15** [comment]
I have also tried invoking the parameter network name and subnet name and the outcome is as follows

[root@infcchfwtnd01 chef-repo]#  knife azure server create -N azuredev01 --azure-vm-size Medium --azure-source-image ecint-std-centos67-v01 --azure-service-location 'Central US' --azure-storage-account saclrsdiglcdev01 --azure-network-name nwc-ecint --azure-subnet-name nwc-ecint-dev --ssh-user admin --ssh-password '****'

...WARN: ResourceNotFound : The hosted service does not exist.
WARN: Unable to find hosted(cloud) service:ResourceNotFound : The hosted service does not exist.
......WARN: ResourceNotFound : No deployments were found.
.WARN: BadRequest : The virtual network nwc-ecint does not exist.
FATAL: Unable to create role:BadRequest : The virtual network nwc-ecint does not exist.
ERROR: Failed to create the server -- exception being rescued: exception class/object expected
WARNING: Cleaning up resources...
..WARNING: Deleted created DNS: az-5938216af952

**Comment by dheerajd-msys** [comment]
@shridevops15,

According to the capture process for Linux VMs, all Linux images must be deprovisioned by running the waagent command with the -deprovision option. Then you can choose "I have run waagent-deprovision on the virtual machine" to indicate that the operating system is prepared to be an image.

I followed the steps and was able to create the VM with created Image.
Please run command `waagent -deprovision` in the VM which you want to get imaged.

Now during image creation you need to select the option "I have run waagent-deprovision on the virtual machine" and complete.

Thanks

**Comment by matkam** [comment]
To create the image:
- Run on the VM:
  `sudo waagent -deprovision+user`
  `sudo rm -rf /etc/chef/*`

- Shut down the VM
- "Capture" the VM

**Comment by Vasu1105** [comment]
@shridevops15 are you still facing this issue with the above solutions ?

**Comment by Vasu1105** [comment]
@shridevops15  reopen if you are still facing issue with given solution by @matkam
