### ISSUE TITLE
Break up the README.

### ISSUE THREAD

**Issue by jjasghar** [chef/knife-azure#369]
The main readme has way too much information in it. We need to break it up in specific docs, for instance:

- ARM
- ASM
- Configuration
- etc

Maybe create a `docs/` directory and link off the main README to the specific sections.

**Comment by NimishaS** [comment]
:+1: @jjasghar

**Comment by Vasu1105** [comment]
@jjasghar  will be working on this.

**Comment by Vasu1105** [comment]
@jjasghar  Changes related to this issue is merged. Closing this issue.
