### ISSUE TITLE
Knife azurerm server create (subnet in use)

### ISSUE THREAD

**Issue by mhugley** [chef/knife-azure#411]
I am trying to add a vm to a vnet-subnet that has other servers. I keep getting this error. 

ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"**InUseSubnetCannotBeUpdated**\",\r\n    \"message\": \"**Subnet default is in use and cannot be updated**.\",\r\n    \"details\": []\r\n  }\r\n}"}]}}

The code that I am using is:
`knife azurerm server create --azure-resource-group-name test-ecosystem --azure-vnet-name test-ecosystem-vnet --azure-vnet-subnet-name default --azure-storage-account test1 --azure-vm-name iiswebserver -N iiswebserver --azure-service-location westus --azure-image-reference-publisher MicrosoftWindowsServer --azure-image-reference-offer WindowsServer --azure-image-reference-sku 2012-R2-Datacenter --azure-image-reference-version latest -x user -P password -r 'recipe[iis::default]' -c /root/chef-repo/.chef/knife.rb --yes`

Is this a bug or is something wrong with the code above?

**Comment by Vasu1105** [comment]
@mhugley  what version of knife-azure you are using  ?

**Comment by mhugley** [comment]
I am also using 1.6.0. It keeps happening to me. I change the computer name and run it again and it did the same. I also tried from another computer and the same happened.

**Comment by Vasu1105** [comment]
@mhugley  Also add your detailed log using -VV option plus details about your  vnet and subnet for e.g. how many subnet that vnet has etc.

**Comment by mhugley** [comment]
Thanks for getting back with me. I think there is something wrong with my vnet. I was able to create a new one with a subnet and it all worked the way it should.

Whenever I run the command it states that its not meant for production servers because its still in alpha. Is this gonna change or is there more testing that needs to take place?

**Comment by Vasu1105** [comment]
@mhugley  knife-azure currently supports only basic ARM functionality and that's why the message is shown "its not meant for production servers because its still in alpha". For complex scenarios ASM commands should be used.

I am closing this issue. Please re-open if you face this issue.
