### ISSUE TITLE
empty result after setup

### ISSUE THREAD

**Issue by inscrutabledude** [chef/knife-azure#422]
Hi All,

I have a feeling this isn't the right place to put this, but I cannot find any other online forum to discuss it.

I've followed several install/setup guides for knife-azure.  When I run knife azure image list, I get results.

Anything else, including "knife azure server list" returns an empty result.  There ARE servers in my subscription, yet nothing is seen.  If someone could point me in the right direction that would be great.  I can provide knife.rb settings etc if needed.

I'm running this on the Azure Marketplace chef server.

Thanks!

**Comment by NimishaS** [comment]
@inscrutabledude , I tried running `knife azure server list` command and it listed all the VMs successfully. I think there may be a difference in the region in which your VMs are created and the region which knife-azure is using. By default, knife-azure uses `West-US`.
You can mention region in your `knife.rb` file like this:
```
knife[:region] = 'us-east-1'
```

**Comment by inscrutabledude** [comment]
Hi Nimisha,

Just a thought here; for a command that per the docs pulls ALL available instances, having a default that pulls only part makes no sense.  How would you run the command if you wanted ALL?  Also, that default isn't mentioned in any docs that I had access to. 

You should seriously consider making the default be actually ALL. 

Thanks,

Bruce

**Comment by NimishaS** [comment]
@inscrutabledude ,  AWS portal also shows servers and all other entities for the selected region only. Some entities (e.g. EC2 SSH keypair) of one region are not accessible by the other regions. So it makes sense to show servers for a particular region. However I'll still discuss the use-case that you have suggested with the Chef team.

We'll definitely update the doc for the default region. That's missing currently.

**Comment by inscrutabledude** [comment]
Hi Nimisha,

I finally got to try your suggestion. It makes no difference at all.  No matter what I put in as a value, only one VM shows up. 

Do you have any other suggestions?

Bruce

**Comment by NimishaS** [comment]
@inscrutabledude , this is how my knife.rb looks:
```
current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "nimisha"
client_key               "#{current_dir}/client.pem"
validation_client_name   "client-validator"
chef_server_url          "https://api.opscode.com/organizations/org"
cookbook_path            ["#{current_dir}/../cookbooks"]
knife[:azure_publish_settings_file] = "<path to publishsettings file>"
```

`knife azure server list` works fine with this configuration. Can you please verify if you are giving the `publishsettings file` or `subscription_id` for the correct account?

**Comment by NimishaS** [comment]
@inscrutabledude, any updates here?

**Comment by NimishaS** [comment]
Sorry we weren't able to reproduce your issue. If you're still experiencing this issue please provide additional information and we'll be happy to help again.
