### ISSUE TITLE
Knife Azure does not work with berkshelf

### ISSUE THREAD

**Issue by gmmeyer** [chef/knife-azure#423]
Knife Azure requires, though the other azure gems, ms_rest_azure 0.2.3, which (for whatever reason) depends on json 1.7. 

Json 1.7 was released in 2013 and does not even compile on my Macbook. This means that every time I try to run it with berkshelf, I get the following error:

```
in `raise_if_conflicts': Unable to activate ms_rest_azure-0.2.3, because json-2.0.3 conflicts with json (~> 1.7) (Gem::ConflictError)
```

Can the relevant azure gems be updated easily? If so, we should do it.

**Comment by NimishaS** [comment]
Fixed in `knife-azure 1.8.0`.
