### ISSUE TITLE
Error Deploying multiple VM's in Same cloud Service

### ISSUE THREAD

**Issue by sernapallyanurag** [chef/knife-azure#431]
``
FATAL: Unable to create role:ConflictError : The specified deployment slot Production is occupied.
ERROR: Failed to create the server -- exception being rescued: exception class/object expected
``
I have checked for the error and it says to change role of one of the VM's to staging. How can we do that using knife.

**Comment by NimishaS** [comment]
@sernapallyanurag , Are you using ASM command `knife ec2 server create`? Can you please share how are you creating multiple VMs?

**Comment by sernapallyanurag** [comment]
Yes I am using ASM. I am running ``knife azure server create`` in multiple threads simultaneously to create VM's in parallel under same cloud service name which I found out to be a constraint in ASM. Please suggest a workaround if one exists or we can close the issue

**Comment by NimishaS** [comment]
@sernapallyanurag , this kind of issue was reported earlier too. Old ASM API's have some limitation for concurrent requests. A workaround for this would be to use `knife azurerm server create` command which utilizes the ARM APIs.

**Comment by sernapallyanurag** [comment]
Thank you for the response @NimishaS . I am closing this issue.
