### ISSUE TITLE
Changes in Azure Xplat CLI broke the knife-azure's login method 

### ISSUE THREAD

**Issue by SimonKaluza** [chef/knife-azure#432]
It seems azure-cli no longer uses the string `"AzureXplatCli"` in `cmdkey` to store relevant Azure login credentials, so the credential check used in knife-azure at https://github.com/chef/knife-azure/blob/eb8fe934fe38c28bbaadd91941cd9c6dcaad17b7/lib/chef/knife/azurerm_base.rb#L186
fails even if a user has successfully used the xplat azure-cli to login to Azure.

**Comment by NimishaS** [comment]
@SimonKaluza , the recent versions of xplat-cli uses `/.azure/accessTokens.json` file to store the credentials by default. We are checking the version of xplat-cli first and based on the using the `credential manager` or `/.azure/accessTokens.json`. Please check the If-Else block: https://github.com/chef/knife-azure/blob/eb8fe934fe38c28bbaadd91941cd9c6dcaad17b7/lib/chef/knife/azurerm_base.rb#L184.

We have verified that this is working successfully.

**Comment by NimishaS** [comment]
@SimonKaluza , any updates here? Do you see some kind of failure?

**Comment by SimonKaluza** [comment]
@NimishaS sorry for the delay.  

This issue seems to be fixed in the commit you linked, I was running the latest released version (1.7.0), but not HEAD.
