### ISSUE TITLE
'--node-ssl-verify-mode none' does not write appropriate value to resulting client.rb

### ISSUE THREAD

**Issue by toolboc** [chef/knife-azure#435]
using `--node-ssl-verify-mode none` referred to in https://github.com/chef/knife-azure/blob/master/docs/ARM.md  does not create an entry of `ssl_verify_mode :verify_none` in the resulting client.rb as should be expected.  

![image](https://cloud.githubusercontent.com/assets/2018336/26088705/45b076bc-39be-11e7-877b-e50ccd783e37.png)

![image](https://cloud.githubusercontent.com/assets/2018336/26088762/9299d996-39be-11e7-87c5-c8129c07b7fe.png)

See chef documentation @ https://docs.chef.io/knife_bootstrap.html:
_--node-ssl-verify-mode PEER_OR_NONE
Set the verify mode for HTTPS requests.
Use none to do no validation of SSL certificates._

**Comment by piyushawasthi** [comment]
@toolboc : We have fix this issue in https://github.com/chef/knife-azure/pull/437
