### ISSUE TITLE
node_name in client.rb always has a '0' appended resulting in auth error

### ISSUE THREAD

**Issue by enrigh0338** [chef/knife-azure#439]
when running the command:

knife azurerm server create ... -N "myNodeName" ...

knife registers 'myNodeName' with the Chef server but on the node the client.rb file shows the node name as 'myNodeName0' (note the trailing '0'). This means the node cannot authenticate with the Chef server. If i rdp to the node, delete the added '0' from the node name and run chef-client manually everything is fine. I have no clue where that trailing '0' comes from.

**Comment by enrigh0338** [comment]
is anyone else experiencing this? I can't be the only one.

**Comment by NimishaS** [comment]
Fixed in `knife-azure 1.8.0`.
