### ISSUE TITLE
Can not create vms in required availability set (ARM)

### ISSUE THREAD

**Issue by Ranjith9** [chef/knife-azure#446]
Trying to create a VM in a required Availability Set and facing following errors.

1) ERROR: Addition of a VM with managed disks to non-managed Availability Set or addition of a VM with blob based disks to managed Availability Set is not supported. Please create an Availability Set with 'Aligned' SKU in order to add a VM with managed disks to it.

2) ERROR: Could not find member 'sku' on object of type 'AvailabilitySet'. Path 'sku'.

3) ERROR: Could not find member 'managed' on object of type 'Properties'. Path 'properties.managed', line 1, position 114.
DEBUG: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"target\": \"availabilitySet.properties.managed\",\r\n    \"message\": \"Could not find member 'managed' on object of type 'Properties'. Path 'properties.managed', line 1, position 114.\"\r\n  }\r\n}"}]}}

**Comment by piyushawasthi** [comment]
@Ranjith9 - Currently `availability set` option only applicable with ASM also `availability set` limit is 2-5. I have verified with following command and it create VM with availability set successfully.

```
knife azure server create --azure-service-location 'WEST US' --azure-source-image 'bd507d3a70934695bc2128e3e5a255ba__RightImage-Windows-2012-x64-v14' -x azure -P azure@123 --bootstrap-protocol cloud-api -c 'D:\chef-repo\.chef\knife.rb' --tcp-endpoints '3389:3389' --daemon service --azure-dns-name 'ammy-win12-1' -N 'ammy-win12-1' --azure-availability-set "ammy"
```

Please refer and compare with your command and let me know in case of any concerns.

**Comment by NimishaS** [comment]
@Ranjith9 , can you please share the steps that you are following to add `availability set` in ARM?

**Comment by Ranjith9** [comment]
I was trying to add VMs to an existing availability set. I added availability set property to "Microsoft.Compute/virtualMachines" 

"availabilitySet"=> ({
                  "id"=> "[resourceId('Microsoft.Compute/availabilitySets', variables('availabilitySetName'))]"
 } if  params[:azure_availability_set] != 'null'),

in server create i added availability set to options and default value is null.

Its working If I'm adding VM to an existing  availability set

**Comment by NimishaS** [comment]
@Ranjith9 , as @piyushawasthi suggested that currently knife-azure ARM command doesn't support `availability set` option. This is a new feature. I have created https://github.com/chef/knife-azure/issues/451 and closing this one to avoid confusion due to the description of the card.
