### ISSUE TITLE
Bootstrapping in Azurerm in not happenning fully.

### ISSUE THREAD

**Issue by Ranjith9** [chef/knife-azure#449]
I was trying to create VMs assigning roles in command 'knife azurerm server create'. The template is able to download Chef-client but the roles are not affecting the VM. I tried to ssh into the newly created VM and run Chef-client over there. It gives me '401 Unauthorized' error.

**Comment by NimishaS** [comment]
@Ranjith9 , please share the command that you are trying and the logs using -VV option.

**Comment by Ranjith9** [comment]
@NimishaS , please find the command below, which I'm trying to execute : 

"knife azurerm server create --azure-resource-group-name 'Ranjith' -N 'test' --azure-service-location 'CentralIndia' --azure-storage-account 'ranjithstorage' --azure-storage-account-type 'Standard_LRS' --azure-vnet-name vnet_1  --azure-vnet-subnet-name subnet_1  --azure-vm-size 'Small' --azure-image-reference-publisher 'Canonical' --azure-image-reference-offer 'UbuntuServer' --azure-image-reference-sku '16.04-LTS' --azure-image-reference-version 'latest' --ssh-user 'ubuntu' -P ubuntu@12345  --azure-vm-name 'test2' -r "role[apache]" -VV" .

The VM is getting created successfully but roles are not affecting the machine. 
Creating Virtual Machine....
Virtual Machine creation successfull.
Deployment name is: test2_deploy
Deployment ID is: /subscriptions/xxxx-xxxx-xxxx-xxxx-xxxx/resourceGroups/Dengine/providers/Microsoft.Resources/deployments/test2_deploy
VM Details ...
-------------------------------
Virtual Machine name is: test2
Virtual Machine ID is: /subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/Dengine/providers/Microsoft.Compute/virtualMachines/test2
Server Name                            test2
Size                                   Standard_A1
Provisioning State                     Succeeded
Location                               CentralIndia
Publisher                              Canonical
Offer                                  UbuntuServer
Sku                                    16.04-LTS
Version                                latest
OS Type                                Linux
Public IP address                      xx.xx.xx.xx
FQDN                                   test2.centralindia.cloudapp.azure.com


I logged into the created VM and tried to execute the Chef-client and it throws error like the following : 

Starting Chef Client, version 13.2.20

================================================================================
Chef encountered an error attempting to load the node data for "test0"
================================================================================

Authentication Error:
---------------------
Failed to authenticate to the chef server (http 401).

Server Response:
----------------
Failed to authenticate as 'test0'. Ensure that your node_name and client key are correct.

Relevant Config Settings:
-------------------------
chef_server_url   "https://api.chef.io/organizations/xxxx"
node_name         "test0"
client_key        "/etc/chef/client.pem"

If these settings are correct, your client_key may be invalid, or
you may have a chef user with the same client name as this node.
.
.
.
 - AzureExtension::ExceptionHandler
Running handlers complete
[2017-08-03T06:31:42+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 02 seconds
[2017-08-03T06:31:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-08-03T06:31:42+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-08-03T06:31:42+00:00] ERROR: 401 "Unauthorized"
[2017-08-03T06:31:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

For other cloud vendors its working fine but not for Azure. Please help me in this. Thank you.

**Comment by Ranjith9** [comment]
Hi,
I found the bug and now its working fine. 
In deployment template the condition for chef_node_name is 
"[concat(parameters('chef_node_name'),copyIndex())]"  which is for server_count >1
If another condition put there "[concat(parameters('chef_node_name'))]" for server_count =1
It works.

Another issue is if server_count > 1, only one node is creating.

**Comment by harikesh-kolekar** [comment]
This has been fixed in PR: https://github.com/chef/knife-azure/pull/447

**Comment by NimishaS** [comment]
Fixed in `knife-azure 1.8.0`.
