### ISSUE TITLE
Servers that are created using plugin is not getting registered to my chef-server

### ISSUE THREAD

**Issue by Nikhil424** [chef/knife-azure#450]
Here If I create servers is azure using 'knife azurerm' plugin, I can see server is getting created but not getting attached to my chef setup. Still I can list the servers using plugin 'knife azurerm server list' that are created in azure.
Before this was working as it was registering the new node/client to my chef-master now its not doing it.

1) The below pasted are the output which I had got earlier(opscode-server):

WARN: Azurerm subcommands are experimental and of alpha quality. Not suitable for production use. Please use ASM subcommands for production.
WARN: Azurerm subcommands are experimental and of alpha quality. Not suitable for production use. Please use ASM subcommands for production.
**Creating new client for test-vm
Creating new node for test-vm**
INFO:Resource Group XXXXX already exist. Skipping its creation.
INFO:Adding new VM test-vm55 to this resource group.
Creating Virtual Machine....

2)This time it is not creating any client/node for chef and the output is posted below(custom chef-server):

WARN: Azurerm subcommands are experimental and of alpha quality. Not suitable for production use. Please use ASM subcommands for production.
WARN: Azurerm subcommands are experimental and of alpha quality. Not suitable for production use. Please use ASM subcommands for production.
INFO:Resource Group XXXXX already exist. Skipping its creation.
INFO:Adding new VM test-vm5 to this resource group.

**NOTE: I am facing this issue only if we use chef-server hosted in a machines and will work fine if we use the manage.opscode.com as our chef-server.**

**Comment by Ranjith9** [comment]
Even I'm facing the same issue.... first i thought its a port issue. I opened all ports of my Chef-server but still Node and Client are not registering with the Chef-server. 

Registering the node and client using **knife-azure plugins** will happen in only opscode servers.........??

**Comment by Nikhil424** [comment]
When I use opscode server node is getting registered, the same doesn't work if I use my Chef-Server.

**Comment by NAshwini** [comment]
Hi @Nikhil424,
I am able to register azure vm on hosted as well as standalone server with below command 
``` bundle exec knife azurerm server create  --azure-resource-group-name AshResourceGrpName  --azure-vm-name ash-win --azure-service-location 'westus'  --azure-image-os-type windows  -x azure -P azure@123456 -r "recipe[test_cbk]" -c D:\chef-repo_standalone_azure\.chef\knife.rb -VV ```

-- For standalone server I have used configuration as 
```chef-manage : 2.5.4,  chef-server-core: 12.16.9, azure -0.10.9 ```

please share the command that you are trying, the versions and the logs.

**Comment by NAshwini** [comment]
@Nikhil424: any updates ?

**Comment by Babu2000** [comment]
@Ashwini, knife-azure(1.7.0) does not work with latest chefdk (2.3.1). knife command is giving gem collision error. Could you please let me know which knife-azure version is compatible with chefdk (2.3.1)? or let me working version compatibles.

**Comment by NAshwini** [comment]
@Babu2000, Please refer solution to your question #461

**Comment by NimishaS** [comment]
Sorry we weren't able to reproduce your issue. If you're still experiencing this issue please provide additional information and we'll be happy to help again.
