### ISSUE TITLE
knife azurerm command returns "azure: not recognized as an internal or external command"

### ISSUE THREAD

**Issue by savishy** [chef/knife-azure#466]
I have been breaking my head over this for a day now and could not understand what's going wrong. 

`knife azurerm server create` , with correct options as in your documentation, returns:

```
ERROR: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of azure -v ----
STDOUT:
STDERR: 'azure' is not recognized as an internal or external command,
operable program or batch file.
---- End output of azure -v ----
Ran azure -v returned 1

```

The most I can see is that it seems to be trying to use the `azure` command (legacy?) instead of the newer `az` command, that comes from the newer Azure CLI. 

* Knife Azure Version: 1.8.0
* OS: Windows 2012R2 DataCenter
* Powershell 5.1
* Azure CLI 2.0

**Comment by Vasu1105** [comment]
@savishy Could you please post the command with all options that you are using it will be easy for us to debug

**Comment by savishy** [comment]
The error is reproduced even without any options, but with a Knife.rb present in the working directory.

Here's my knife.rb

```
current_dir = File.dirname(__FILE__)
log_level       :info
log_location    STDOUT
# provisioning a chef server so we don't have a chef server yet
local_mode  true
cookbook_path       ["#{current_dir}/cookbooks"]
azure_subscription_id "azure sub ID"
azure_tenant_id "tenant id from service principal"
azure_client_id "some client id"
azure_client_secret "some client secret
```

With this, I now run `knife azurerm server create` without any options. As you can see from output below, it is trying to run `azure -v` which is not a command from Azure CLI 2.0.

```
PS > knife azurerm server create
ERROR: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of azure -v ----
STDOUT:
STDERR: 'azure' is not recognized as an internal or external command,
operable program or batch file.
---- End output of azure -v ----
Ran azure -v returned 1
```

**Comment by vishagilityroots** [comment]
Hello, any updates or responses to this? 
We are trying to use Knife at our organization as part of a "Chef-only" effort to provision infrastructure. I am aware I can use workarounds for this issue (such as using plain vanilla Azure CLI to perform the create action, for example) - but the point is I'd like some confirmation of this issue please, and when/if it's going to be fixed. Thank you!

**Comment by piyushawasthi** [comment]
Hi @savishy , @vishagilityroots - This issue is fixed in PR: https://github.com/chef/knife-azure/pull/467.

**Comment by piyushawasthi** [comment]
Hi @savishy, We have added Azure CLI2.0 support in PR: https://github.com/chef/knife-azure/pull/467, which is merged. Will you please close this issue.

**Comment by savishy** [comment]
Thanks for the quick action. I have not gotten a chance to verify the fix for this issue. Is is still alright to close it?

**Comment by piyushawasthi** [comment]
Hi @savishy, Currently we have provided support of both Azure CLI1.0 and 2.0. Please verify as per your convenience if all good then close this issue.

**Comment by dheerajd-msys** [comment]
@savishy As mentioned in above comment, Issue is fixed so closing this now. Please feel free to reopen if you face any difficulty.

**Comment by savishy** [comment]
Alright sure. Since I had to move away from Chef for a bit I haven't been able to action this. Thanks for the quick response!
