### ISSUE TITLE
Azure VM not created on using knife azurerm server create command

### ISSUE THREAD

**Issue by jayaen** [chef/knife-azure#469]
I have chefdk-2.5.3-1-x86 installed in windows 7 machine 
Trying below command with --verbose  results in error 
Please help to resolve the issue at earliest
knife azurerm server create  --azure-resource-group-name 'RG_LBMultiTier'  --azure-vm-name 'AppTierVM3'  --azure-vm-size Small  --azure-storage-account 'samultitiervms2' --azure-service-location 'East Asia' --azure-image-os-type windows   -x 'windows' -P 'jgfdsgsdfsaf' --verbose

Node AppTierVM3 exists, overwrite it? (Y/N) Y
Client AppTierVM3 exists, overwrite it? (Y/N) Y
Creating new client for AppTierVM3
Creating new node for AppTierVM3
ERROR: Something went wrong. Please use -VV option for more details.

knife.rb file 
current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "jayaen"
client_key               "#{current_dir}/jayaen.pem"
chef_server_url          "https://api.chef.io/organizations/xxxxxxx"
cookbook_path            ["#{current_dir}/cookbooks"]
knife[:azure_subscription_id] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
knife[:azure_tenant_id] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
knife[:azure_client_id] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
knife[:azure_client_secret] = "xxxxxxxxxxx"

**Comment by Vasu1105** [comment]
@jayaen could you please post the log using -VV option in your command. That will give us detailed output.

**Comment by jayaen** [comment]
Thanks , after including --winrm-user and password it works

**Comment by KomalNimje** [comment]
> Thanks , after including --winrm-user and password it works

How to include --winrm-user and password?

**Comment by dheerajd-msys** [comment]
@KomalNimje In your command just append `--connection-user <USERNAME>` and `--connection-password <PASSWORD>` along with other required parameters.

Please refer https://github.com/chef/knife-azure/blob/master/docs/ARM.md#azure-server-create-subcommand for more information.

**Comment by KomalNimje** [comment]
![cheferror](https://user-images.githubusercontent.com/46679024/77159901-46af7d00-6acc-11ea-847d-fe693b54bc27.PNG)

@dheerajd-msys  This is as I'm trying. Still facing the error.
Please let me know if there is anything.
