### ISSUE TITLE
Creating VM using custom azure images

### ISSUE THREAD

**Issue by abhisheks255** [chef/knife-azure#474]
Hi,

How can we create a VM using azure custom images?? As far as i know , we can create vm using azure marketplace images , Do we have any functionality for deploying VM using our own custom images?

**Comment by dheerajd-msys** [comment]
@abhisheks255 Please refer https://github.com/chef/knife-azure/issues/342 for command to create VM using custom image. You can follow the instructions on comments for capturing the image and then try to create the vm using `knife azure server create` out of that custom image.

Thanks,

**Comment by abhisheks255** [comment]
How can i use --azure-source-image option with knife azurerm , according to my understanding this option works with knife azure but how can we create VM using custom images with azurerm ? I am getting this Error: invalid option: --azure-source-image when i use it with knife azurerm server create. Is there any way out with knife azurerm command for creating VM using custom images ?

**Comment by piyushawasthi** [comment]
hi @abhisheks255 for custom image you need to pass `--azure-image-reference-publisher` `--azure-image-reference-sku` and version if required with knife azurerm. Please check and let us know in case of any concerns. Also If all good please closed this issue.

**Comment by dheerajd-msys** [comment]
@abhisheks255 Got a chance to try out above options with `knife-azurerm`? Please let us know.

Thanks

**Comment by Vasu1105** [comment]
@abhisheks255 if you still need any help let us know. I am closing this for now.
