### ISSUE TITLE
azure_mgmt_resources conflict

### ISSUE THREAD

**Issue by DavidMcCarley** [chef/knife-azure#477]
After install of knife-azure I get this error with any knife commands

E:/Chef/chefdk/embedded/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts': Unable to activate knife-azure-1.8.0, because azure_mgmt_resources-0.16.0 conflicts with azure_mgmt_resources (= 0.9.0) (Gem::ConflictError)

**Comment by sonofhammer** [comment]
I had the same issue. I Was able to resolve it by uninstalling ChefDK 3.0.36 and installing version 2.5.3. It looks like the latest stable version of ChefDK is referencing azure_mgmt_resources 0.16.0 here: https://github.com/chef/chef-dk/blob/v3.0.36/Gemfile.lock, whereas knife-azure wants version 0.9.0

**Comment by dheerajd-msys** [comment]
Closing this issue based on above comments.

Thanks
