### ISSUE TITLE
401 when provisioning windows VMs

### ISSUE THREAD

**Issue by phoellig** [chef/knife-azure#49]
This is probably a configuration issue rather than a bug, but I've followed the docs as best I can and am having some trouble provisioning windows VMs, linux ones work fine.

I'm using 1.2.0, which I checked out and built a few days back (Thursday, I believe).

I created a windows VM in Azure, followed the docs on the knife-windows project to configure winrm (re: ran all of the commands that are shown there), ran sysprep on the machine, and captured an image from it. 

Then I configure my knife.rb with my subscription and cert info (which works since I can provision linux VMs fine) and feed that image to the knife azure server create command as follows:

```bash
knife azure -VV server create --azure-service-location 'West US' --winrm-user myusername --winrm-password password123? --azure-source-image quickchef-windows2008 --azure-dns-name winChef1234 --azure-vm-size Small --azure-storage-account myvmstorage --template-file windows-template.erb
```

The VM gets created with the WinRM endpoint and then fails to connect with a 401. I'm guessing it's a azure/winrm/sysprep issue, but there isn't really documentation that I've been able to find discussing it. Here is the long output from the command that I've run https://gist.github.com/sethvargo/5980750

Thanks!

(I moved the stacktrace to a gist to improve readability - @sethvargo)

**Comment by siddheshwar-more** [comment]
@phoellig 
Seems this issue is resolved.
