### ISSUE TITLE
azure_mgmt_resources and  azure_mgmt_network conflict errors

### ISSUE THREAD

**Issue by fegonfe** [chef/knife-azure#490]
# Version:

1.8.0

# Environment: [Details about the environment such as the Operating System, cookbook details, etc...]
Windows 10.
ChefDK: 3.3.23

# Steps to Reproduce:
knife azure image list

# Actual Result:

Traceback (most recent call last):
        18: from C:/opscode/chefdk/bin/knife:307:in `<main>'
        17: from C:/opscode/chefdk/bin/knife:307:in `load'
        16: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/bin/knife:24:in `<top (required)>'
        15: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/application/knife.rb:161:in `run'
        14: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/knife.rb:215:in `run'
        13: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/knife.rb:152:in `subcommand_class_from'
        12: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
        11: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:95:in `load_command'
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:85:in `load_commands'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:85:in `each'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:85:in `block in load_commands'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33-universal-mingw32/lib/chef/knife/core/subcommand_loader.rb:85:in `load'
         6: from C:/Users/fferre/AppData/Local/chefdk/gem/ruby/2.5.0/gems/knife-azure-1.8.0/lib/chef/knife/azurerm_base.rb:21:in `<top (required)>'
         5: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         4: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
         3: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
         2: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
         1: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
C:/opscode/chefdk/embedded/lib/ruby/2.5.0/rubygems/specification.rb:2325:in `raise_if_conflicts': Unable to activate knife-azure-1.8.0, because azure_mgmt_resources-0.17.1 conflicts with azure_mgmt_resources (= 0.9.0), azure_mgmt_network-0.17.3 conflicts with azure_mgmt_network (= 0.9.0) (Gem::ConflictError)

**Comment by tas50** [comment]
This will be resolved when we make the release of knife-azure 1.9, which will happen very soon.

**Comment by btm** [comment]
knife azure 1.9.0 has been released.
