### ISSUE TITLE
Azure VM not created on using knife azurerm server create command

### ISSUE THREAD

**Issue by KomalNimje** [chef/knife-azure#519]
# Version:
I have chefdk-4.7.73-1-x64 installed on Windows 10.
Ruby version - ruby 2.6.5p114

# Environment:
knife.rb

current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "komalnimje1"
client_key               "#{current_dir}/komalnimje1.pem"
chef_server_url          "https://manage.chef.io/organizations/chef-org-win"
cookbook_path            ["#{current_dir}/../cookbooks"]

validation_client_name   "myorg-validator"
validation_key           "#{current_dir}/chef-org-win-validator.pem"
knife[:azure_tenant_id] =         "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
knife[:azure_subscription_id] =   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
knife[:azure_client_id] =         "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
knife[:azure_client_secret] =     "***********"

# Scenario:
Trying to automate deployment of a Azure Virtual Machine with Chef

# Steps to Reproduce:
knife azurerm server create `
    --azure-resource-group-name rg-chefdeployment `
    --azure-storage-account store `
    --azure-vm-name chefvm `
    --azure-vm-size 'Standard_DS2_v2' `
    --azure-service-location 'centralindia' `
    --azure-image-reference-offer 'WindowsServer' `
    --azure-image-reference-publisher 'MicrosoftWindowsServer' `
    --azure-image-reference-sku '2016-Datacenter' `
    --azure-image-reference-version 'latest' `
    -x myuser -P myPassword123 `
    --tcp-endpoints '80,3389' `
    --chef-daemon-interval 1 `
    -r "recipe[webserver]"

# Expected Result:
Creating new client for chefvm
Creating new node for chefvm
Creating ResourceGroup....
Creating Virtual Machine....
Virtual Machine creation successful.

# Actual Result:
C:/Users/komalni/AppData/Local/chefdk/gem/ruby/2.6.0/gems/knife-azure-2.0.13/lib/chef/knife/helpers/azurerm_base.rb:36:in `require_relative': cannot load such file -- C:/Users/komalni/AppData/Local/chefdk/gem/ruby/2.6.0/gems/knife-azure-2.0.13/lib/chef/azure/resource_management/ARM_interface (LoadError)
        from C:/Users/komalni/AppData/Local/chefdk/gem/ruby/2.6.0/gems/knife-azure-2.0.13/lib/chef/knife/helpers/azurerm_base.rb:36:in `block (2 levels) in included'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23-universal-mingw32/lib/chef/knife.rb:241:in `each'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23-universal-mingw32/lib/chef/knife.rb:241:in `load_deps'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23-universal-mingw32/lib/chef/knife.rb:226:in `run'
        from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23-universal-mingw32/lib/chef/application/knife.rb:163:in `run'
        from C:/opscod
e/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23-universal-mingw32/bin/knife:24:in `<top (required)>'
        from C:/opscode/chef-workstation/modules/chef/../../bin/knife:378:in `load'
        from C:/opscode/chef-workstation/modules/chef/../../bin/knife:378:in `<main>'

**Comment by dheerajd-msys** [comment]
@KomalNimje It seems you've not install Azure Cli in your machine. Please try to follow https://github.com/chef/knife-azure#description and specifically https://docs.microsoft.com/en-us/cli/azure/install-azure-cli. 

Please let us know if there is anything.

**Comment by KomalNimje** [comment]
@dheerajd-msys Thanks for quick reply.
I already have AzureCLI installed on my machine. Please check below version.
And instead of config.rb, I'm using knife.rb. Is there any issue with knife.rb?
 
az --version
azure-cli                          2.2.0
command-modules-nspkg              2.0.3
core                               2.2.0
nspkg                              3.0.4
telemetry                          1.0.4
Extensions:
azure-devops                      0.17.0
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\komalni\.azure\cliextensions'
Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

Please let me know if there is anything.

**Comment by dheerajd-msys** [comment]
Thanks @KomalNimje for the update. Doesn't look like any issue with knife.rb. 
We'll check and get back to you.

Linking your command o/p reference : https://github.com/chef/knife-azure/issues/469#issuecomment-601654703

**Comment by dheerajd-msys** [comment]
Hi @KomalNimje We've got issue reproduced. Working to fix this up.
